Fixed numpy divide by zero error converting ECEF for multiple locations.
After the change in commit dde1b9 to use isclose(), this now fails with the
following exception when trying to convert multiple locations (len(z) > 1) and
one or more of them has a divide-by-zero error:
ValueError: The truth value of an array with more than one element is
ambiguous. Use a.any() or a.all()